name: Build Workflow

on:
  workflow_call:
    inputs:
      manifest-path:
        required: true
        type: string
      bundle:
        required: true
        type: string
    
jobs:
  build:
    name: Build ${{ inputs.bundle }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ inputs.bundle }}
          manifest-path: ${{ inputs.manifest-path }}
          cache-key: flatpak-builder-${{ github.sha }}
